# Generated by Django 4.0.2 on 2022-02-06 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('delimiter', models.CharField(choices=[(',', 'Comma (,)'), ('    ', 'Tab (    )'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)')], max_length=4, verbose_name='Column separator')),
                ('quote', models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Quote (')")], max_length=1, verbose_name='String character')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Column name')),
                ('type', models.CharField(choices=[('name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('domain', 'Domain name'), ('phone', 'Phone number'), ('company', 'Company name'), ('text', 'Text'), ('number', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=20, verbose_name='Type')),
                ('range_from', models.IntegerField(null=True, verbose_name='From')),
                ('range_to', models.IntegerField(null=True, verbose_name='To')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schema.schema')),
            ],
        ),
    ]
